### PR TITLE
Replaced Butterknife by Data Binding

### PR DESCRIPTION
**Pull request by rob729**

### CODE REVIEW

**Comment by rob729** [comment]
@sridharjajoo This PR is for issue #21.
Please review this PR.

**Comment by sridharjajoo** [comment]
You should have pulled the latest code base first and then should have started to add new code to it

**Comment by sridharjajoo** [comment]
I saw the merge conflicts. They can be resolved easily. Just follow the basic steps for the same

**Comment by rob729** [comment]
@sridharjajoo I have resolved the conflicts.
Please review the PR.

**Comment by sridharjajoo** [comment]
also could you upload a small gif of the app walkthrough with the above changes

**Comment by sridharjajoo** [comment]
The dimens.xml already exists why create a new one

**Comment by rob729** [comment]
@sridharjajoo I have done the requested changes and also removed the duplicate Dimen.xml file.

**Comment by sridharjajoo** [comment]
Looks good

**Comment by rob729** [comment]
@sridharjajoo is there any else left to be done as you have not merged the PR?

**Pull request merged**
